# Model arguments
model_name_or_path: /mnt/nas_data2/chenjn_workspace/datasets/HF/Qwen/Qwen2.5-1.5B-Instruct
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: /mnt/nas_data2/chenjn_workspace/datasets/common/OpenR1-Math-220k
dataset_num_proc: 48

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: 'no'
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: false
max_length: 16384
max_steps: -1
num_train_epochs: 1
output_dir: output/llm_pro/train/Qwen2.5-1.5B-Open-R1-Distill
overwrite_output_dir: true
per_device_eval_batch_size: 16
per_device_train_batch_size: 2
max_seq_length: 4096
report_to:
- wandb
wandb_project: open-r1-math-220k
run_name: Qwen2.5-1.5B-Open-R1-Distill
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
use_liger_kernel: true
warmup_ratio: 0.05